# Generated by Django 3.0 on 2020-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('PROFESSIONAL', 'Professional'), ('BUSINESS', 'Business'), ('RELIGIOUS', 'Religious'), ('POLITICS', 'Politics')], default='Personal', max_length=13),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Farming', max_length=30),
        ),
    ]
